### PR TITLE
Add support for PEP 517/518

### PR DESCRIPTION
**Pull request by botant**
Here is my attempt to add support for PEP 517/518.  Tests can be improved, and documentation needs to be updated, but I wanted to know what you think before continuing.  Thanks!

### CODE REVIEW

**Comment by ionelmc** [comment]
At first glance this looks good. How will the develop mode be handled in pep518 mode?

**Comment by botant** [comment]
I haven't thought about develop mode yet to be honest, mainly because I
don't have much experience with it.  How does it work today under
bdist_wheel?

**Comment by ionelmc** [comment]
I think for now we need to disallow that (iow: give clear error to use that pep518 mode can't be used with develop mode).

There's no support for it yet, see https://github.com/pypa/pip/pull/8212 for what's worked on.

**Comment by botant** [comment]
Just committed a fix and test for the ``patch`` function.

About develop mode, am I right in interpreting that we currently don't build the wheel at all?  I'm a bit puzzled about the idea of building a wheel *and* editing it in one go, kind of compiling and editing at the same time.  I might be short sighted, but I can't see how these two things would go together.

**Comment by botant** [comment]
On a different note, we should add Python 3.8 to ``tox.ini`` since it is supported by ``tox``.

Also, would you be open to adding Black and pre-commit to the project?  I could have a stab at that in another PR.

**Comment by ionelmc** [comment]
Ah ... I think I may have forgotten that develop mode already disables the plugin.

Black - not really a fan of it. Pre-commit yes, but I already have some of the configuration of it in cookiecutter-pylibrary - it's just a matter of applying it (I usually do that before a release). It will have the 3.8 config so I wouldn't waste time with those.

**Comment by botant** [comment]
Black is indeed an acquired taste :-)

About the PR: this seems to work, but I'm relatively new to the inner
workings of tox.  I still need to update changelog, documentation, etc.
before it can be merged.

**Comment by ionelmc** [comment]
Well, I mean, if black will get you contribute more we can add it ... there's not much code in this project so it doubt it would produce lots of uglyness :) But wait till I reapply that cookiecutter so we can avoid conflicts.

**Comment by botant** [comment]
I do think that Black often produces ugly code, but it is useful for
keeping a consistent style.

I'm keen to spend more time contributing anyway, which feels great and is
very good for learning :-)

**Comment by ionelmc** [comment]
@botant alright so tests seem to pass (not sure what was going on before, maybe travis was having a bad time). How can we get this moving forward?

If you want to have a go at the black config please pull this first: https://github.com/ionelmc/tox-wheel/tree/skel-update

**Comment by botant** [comment]
Up to you, really. If you want, I can configure pre-commit with black,
isort, and things like that.  Otherwise we can move on as is since the
tests are passing.

I haven't changed the documentation yet, and I also don't know if I should
add my name anywhere, like a CONTRIBUTORS file.

Either way, I should be able to push another commit this weekend to finish
this. Just let me know what you think.

Thanks!!

**Comment by ionelmc** [comment]
Well then I can push the skel changes here and you can add the docs/black, yes?

There's a changelog/authors - feel free to change them.

**Comment by botant** [comment]
How about this: you push the skel changes, and I'll modify the
documentation, etc.

I'll add black, isort and pre-commit in another PR, to make the diffs
independent.

How does that sound?

**Comment by ionelmc** [comment]
I don't really care about small PRs - feel free to do whatever you like.

**Comment by ionelmc** [comment]
@botant you want to add anything else? I'm in the mood for making a release.

**Comment by botant** [comment]
Sorry, didn't get to it last weekend. I'll modify the docs and commit by
the end of the day today, if that is ok.

**Comment by ionelmc** [comment]
Can't wait :-) Lemme know when you pushed.

**Comment by botant** [comment]
Done. I've added myself to AUTHORS.rst and updated README.rst.  I've also added a new version to CHANGELOG.rst as 0.X.Y because I don't know what the next version will be, so please fix that.  I didn't add Black to pre-commit.

It's been a pleasure to collaborate, and I'm looking forward to updating all my work projects with the new version!

**Comment by ionelmc** [comment]
Thanks!

**Pull request merged**
